version: '2'
volumes:
    shared-data:
    redis-data:
    web-data:
services:
  audio:
    image: balenablocks/audio
    privileged: true
    ports:
      - 4317:4317
  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    volumes:
      - 'shared-data:/data1'
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: myminio
      MINIO_SECRET_KEY: myminio123
      MINIO_REGION_NAME: myregion
    command: minio server /data1
  controller:
    restart: always
    privileged: true
    build: ./controller
    volumes:
      - 'shared-data:/data/my_data'
    labels:
      io.balena.features.supervisor-api: '1'
